/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;

/**
 *
 * @author isaac
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lresultado = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        bcalcular = new javax.swing.JButton();
        tvalor1 = new javax.swing.JTextField();
        tvalor2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Rmultiplicar = new javax.swing.JRadioButton();
        Rsumar = new javax.swing.JRadioButton();
        Rresta1 = new javax.swing.JRadioButton();
        Rdividir = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lresultado.setBackground(new java.awt.Color(255, 153, 255));
        lresultado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lresultado.setForeground(new java.awt.Color(0, 0, 0));
        lresultado.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(lresultado, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(lresultado, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 20, 500, 90);

        jPanel2.setBackground(new java.awt.Color(0, 255, 204));

        bcalcular.setBackground(new java.awt.Color(0, 153, 153));
        bcalcular.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bcalcular.setForeground(new java.awt.Color(0, 0, 0));
        bcalcular.setText("calcular");
        bcalcular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bcalcularMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bcalcularMouseExited(evt);
            }
        });
        bcalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcalcularActionPerformed(evt);
            }
        });

        tvalor1.setBackground(new java.awt.Color(255, 255, 51));
        tvalor1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tvalor1.setForeground(new java.awt.Color(0, 0, 0));
        tvalor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tvalor1ActionPerformed(evt);
            }
        });

        tvalor2.setBackground(new java.awt.Color(255, 255, 51));
        tvalor2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tvalor2.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("valor2");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("valor1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(bcalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(tvalor1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(tvalor2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tvalor1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tvalor2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(bcalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(20, 120, 500, 290);

        buttonGroup1.add(Rmultiplicar);
        Rmultiplicar.setText("MULTIPLICAR");
        Rmultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RmultiplicarActionPerformed(evt);
            }
        });
        getContentPane().add(Rmultiplicar);
        Rmultiplicar.setBounds(550, 180, 130, 21);

        buttonGroup1.add(Rsumar);
        Rsumar.setText("SUMA");
        Rsumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RsumarActionPerformed(evt);
            }
        });
        getContentPane().add(Rsumar);
        Rsumar.setBounds(550, 90, 80, 21);

        buttonGroup1.add(Rresta1);
        Rresta1.setText("RESTA");
        Rresta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rresta1ActionPerformed(evt);
            }
        });
        getContentPane().add(Rresta1);
        Rresta1.setBounds(550, 120, 130, 21);

        buttonGroup1.add(Rdividir);
        Rdividir.setText("DIVIDIR");
        Rdividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdividirActionPerformed(evt);
            }
        });
        getContentPane().add(Rdividir);
        Rdividir.setBounds(550, 150, 130, 21);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bcalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcalcularActionPerformed
       //settext es para asignar un valor
       //gettext es para mostar que hay en el campo
        float num1=0,num2=0,total=0;
       num1=Float.parseFloat(tvalor1.getText());
       num2=Float.parseFloat(tvalor2.getText());
       
        if (Rsumar.isSelected()) {
            total=num1+num2; 
        }else if (Rresta1.isSelected()) {
            total=num1-num2;
        }else if (Rdividir.isSelected()) {
            total=num1/num2;
        }else if (Rmultiplicar.isSelected()) {
          total=num1*num2;  
        }
       
       
       lresultado.setText(String.valueOf(total));
    }//GEN-LAST:event_bcalcularActionPerformed

    private void tvalor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tvalor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tvalor1ActionPerformed

    private void bcalcularMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bcalcularMouseEntered
      
    }//GEN-LAST:event_bcalcularMouseEntered

    private void bcalcularMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bcalcularMouseExited
       
    }//GEN-LAST:event_bcalcularMouseExited

    private void RmultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RmultiplicarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RmultiplicarActionPerformed

    private void RsumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RsumarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RsumarActionPerformed

    private void Rresta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rresta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rresta1ActionPerformed

    private void RdividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdividirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RdividirActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Rsumar.setSelected(true);
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Rdividir;
    private javax.swing.JRadioButton Rmultiplicar;
    private javax.swing.JRadioButton Rresta1;
    private javax.swing.JRadioButton Rsumar;
    private javax.swing.JButton bcalcular;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lresultado;
    private javax.swing.JTextField tvalor1;
    private javax.swing.JTextField tvalor2;
    // End of variables declaration//GEN-END:variables
}
